### ISSUE TITLE
Configuration to mock captcha

### ISSUE THREAD

**Issue by KrzysztofMadejski** [petabyte-research/redflags#1]
The hack for now is: 

> To turn off captcha validation, edit hu.petabyte.redflags.web.svc.SecuritySvc and add this to validateCaptcha method as the first line:
> 
> if (1==1) return true;

Should be implemented as a configuration setting.

**Comment by juzraai** [comment]
I've just built in the option to turn off captcha. If you set `site.useCaptcha` application property to `false` it will not validate the captcha and also it won't display captcha on the site.

I will include it in the documentation.

**Comment by KrzysztofMadejski** [comment]
Thank you @juzraai! I'll reopen this issue to keep in mind it's not in the documentation yet.
- [x] Include info about `site.useCaptcha` in the development docs

**Comment by juzraai** [comment]
I've added it to the documentation. Currently it's here (but I may reorganize the webapp chapter later):
http://docs.redflags.eu/developer/webapp/basic/#captcha
