### ISSUE TITLE
Country-specific gear configuration

### ISSUE THREAD

**Issue by KrzysztofMadejski** [petabyte-research/redflags#10]
1. How to configure gears so they process only indices from selected sources?
2. How to annotate notices with the source id during import?
3. How to identify sources? Only by country or can it be there multiple sources from each country? I guess yes - if we for example gather low-cost contracts from each of the institution webpages. So maybe an id for source in format of "pl", "pl/warsaw-city"

**Comment by juzraai** [comment]
**Using multiple sources**
You can use multiple sources as long as you can generate valid and unique `NoticeID` objects for each notice.

Currently, information like source or source ID is not managed in _Red Flags_. It's designed for _TED_, and relies on notice IDs used there (`number-year`).

The country is stored in `Data.country`, city is stored in `Data.place` field.

**Annotating notices during import**
If you need to add the source information, you can do the following:

(1) Create a custom notice ID class with an extra `source` field, like:

``` java
public class MyNoticeID extends NoticeID {
  private String source;
  // constructors
  // getSource, setSource
}
```

(2) When you create your own notice iterator (see [cookbook](http://docs.redflags.eu/developer/cookbook/#step-3-add-custom-notice-iterator)), generate `MyNoticeID` objects and fill in `source` field (besides `number` and `year`)

**Processing only selected sources**
(3) Then in your gears you can filter by `source`:

``` java
protected Notice processImpl(Notice notice) throws Exception {
  if (notice.getId() instanceof MyNoticeId) { // type-safety
    MyNoticeId id = (MyNoticeId) notice.getId();
    if ("desired source".equals(id.getSource())) { // filtering
      // processing
    }
  }
  return notice;
}
```

**Comment by KrzysztofMadejski** [comment]
So I believe that we need to redesign the NoticeId so it's not specific for
TED. How about adding the source to the original class?

Also Sub classing won't help old gears processing new notices. Either we
need to reconfigure all the gears or create some kind of general
configuration saying what gears should be enabled for given import command.

@dzierzy - do you have some propositions?

On Wednesday, 15 June 2016, Zsolt Jurányi notifications@github.com wrote:

> _Using multiple sources_
> You can use multiple sources as long as you can generate valid and unique
> NoticeID objects for each notice.
> 
> Currently, information like source or source ID is not managed in _Red
> Flags_. It's designed for _TED_, and relies on notice IDs used there (
> number-year).
> 
> The country is stored in Data.country, city is stored in Data.place field.
> 
> _Annotating notices during import_
> If you need to add the source information, you can do the following:
> 
> (1) Create a custom notice ID class with an extra source field, like:
> 
> public class MyNoticeID extends NoticeID {
>   private String source;
>   // constructors
>   // getSource, setSource
> }
> 
> (2) When you create your own notice iterator (see cookbook
> http://docs.redflags.eu/developer/cookbook/#step-3-add-custom-notice-iterator),
> generate MyNoticeID objects and fill in source field (besides number and
> year)
> 
> _Processing only selected sources_
> (3) Then in your gears you can filter by source:
> 
> protected Notice processImpl(Notice notice) throws Exception {
>   if (notice.getId() instanceof MyNoticeId) { // type-safety
>     MyNoticeId id = (MyNoticeId) notice.getId();
>     if ("desired source".equals(id.getSource())) { // filtering
>       // processing
>     }
>   }
>   return notice;
> }
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/petabyte-research/redflags/issues/10#issuecomment-226136540,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAz4N6SVaABpQz_tc19AejJAbKlvBhbQks5qL8a-gaJpZM4I1TAL
> .

## 

_Krzysztof Madejski_
karolina.wysocka@epf.org.plCode for Poland Program Manager / Koordynator
Koduj Dla Polski
krzysztof.madejski@epf.org.pl / +48 664 082 823
- http://epf.org.pl/*

**Comment by juzraai** [comment]
> How about adding the source to the original class?

I may not understand completely the purpose of the `source` field, but in my point of view, your import function and this extra field are **special functionalities**, so I wouldn't integrate them into the core.

> Sub classing won't help old gears processing new notices

Old gears (_TED_ downloaders, parsers, Hungarian indicators) don't need the `source` field, and you're going to turn most of these gears off in the configuration.

Any custom processing (Polish import, Polish indicators) should be implemented as **new gears**.

> configuration saying what gears should be enabled for given import command.

[Configuration for enabling/disabling gears](http://docs.redflags.eu/developer/engine/#gear-trains) already exists. You can also create [different configuration profiles](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-profiles.html) (_Spring_'s functionality), and when you run the engine, you can tell which profile[s] you want to use.

So for example you can **create configuration profiles** for `importA` and `importB`, then you can run the engine using `importA` profile and after you run it again using `importB`.

**Comment by KrzysztofMadejski** [comment]
Thank you for clarification! :)

On Wednesday, 15 June 2016, Zsolt Jurányi notifications@github.com wrote:

> How about adding the source to the original class?
> 
> I may not understand completely the purpose of the source field, but in
> my point of view, your import function and this extra field are _special
> functionalities_, so I wouldn't integrate them into the core.
> 
> Sub classing won't help old gears processing new notices
> 
> Old gears (_TED_ downloaders, parsers, Hungarian indicators) don't need
> the source field, and you're going to turn most of these gears off in the
> configuration.
> 
> Any custom processing (Polish import, Polish indicators) should be
> implemented as _new gears_.
> 
> configuration saying what gears should be enabled for given import command.
> 
> Configuration for enabling/disabling gears
> http://docs.redflags.eu/developer/engine/#gear-trains already exists.
> You can also create different configuration profiles
> http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-profiles.html
> (_Spring_'s functionality), and when you run the engine, you can tell
> which profile[s] you want to use.
> 
> So for example you can _create configuration profiles_ for importA and
> importB, then you can run the engine using importA profile and after you
> run it again using importB.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/petabyte-research/redflags/issues/10#issuecomment-226170003,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAz4N_jbUOyY5RCUtMqSRNdo-fazj6Tsks5qL-1FgaJpZM4I1TAL
> .

## 

_Krzysztof Madejski_
karolina.wysocka@epf.org.plCode for Poland Program Manager / Koordynator
Koduj Dla Polski
krzysztof.madejski@epf.org.pl / +48 664 082 823
- http://epf.org.pl/*

**Comment by dzierzy** [comment]
We can follow one of @juzraai suggestions (subclassing or extra field 'source') or reuse 'url' field of Notice class, could help determine source using url patterns.
Yet another way is to leave it as-is and define separate gear list within application.yml
