### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by KrzysztofMadejski** [petabyte-research/redflags#15]
I'm going through the dev documentation http://docs.redflags.eu/developer/first/#environment

doing the step `redflags-engine/src/main/resources/application.yml - you have to edit the database connection parameters, in the "GEAR SETTINGS" section.`

In the file there is [a second db config](https://github.com/petabyte-research/redflags/blob/master/redflags-engine/src/main/resources/application.yml.example#L139) mentioned as `kmonitor.inst`. What is it? Do I need to set it up?

**Comment by juzraai** [comment]
Nope, `kmonitor.inst` is needed by 2 of our indicators, you can skip these lines. :)

**Comment by KrzysztofMadejski** [comment]
Thank you!
