### ISSUE TITLE
Scope for pl version

### ISSUE THREAD

**Issue by KrzysztofMadejski** [petabyte-research/redflags#16]
I see that in `redflags-auto.sh` @dzierzy you have set `--scope=epf` while docs are saying that `scope` shsould mention tender ids or years to process. Is it a temporary hack?

Shouldn't we introduce a new parameter that specifies what **source** should be imported (like Hungarian TED or Polish mojepanstwo) and the `scope` could be left as it is?

**Comment by dzierzy** [comment]
I've used --scope parameter to point to different source of data to process. As API mojepanstwo.pl doesn't allow to filter procurement ids at all I've used it as a final solution.

**Comment by KrzysztofMadejski** [comment]
@juzraai is what I'm asking resolved by changing gear configuration?

**Comment by juzraai** [comment]
Creating a custom scope is a/the good solution if you don't want to use TED.

Besides changing scope, indeed, removing TED-related gears from configuration is the other thing needed to avoid TED.

**Comment by KrzysztofMadejski** [comment]
Ok, thanks!
