### ISSUE TITLE
ENGINE_JAR in redflags-auto.sh

### ISSUE THREAD

**Issue by KrzysztofMadejski** [petabyte-research/redflags#17]
In redflags-auto.sh ENGINE parameter should point to target directory, ie. `ENGINE_JAR="$ENGINE_DIR/target/redflags-engine-1.1.0-SNAPSHOT.jar"`

**Comment by dzierzy** [comment]
I didn't modify sh script more than needed. Taarget directory is Maven output dir and jar file should be picked up from there
