### ISSUE TITLE
Doesn't TED allow for tracking changes in notices?

### ISSUE THREAD

**Issue by KrzysztofMadejski** [petabyte-research/redflags#27]
- [ ] `notice.addInfoWarning=The contracting authority could modify the original notice in the additional information documents which can significantly affect the result of the procedure, therefore looking into them is highly recommended.` - Doesn't TED allow for tracking changes?

**Comment by juzraai** [comment]
Documents (notices) are not changing. Instead, new _"Additional information"_ documents are added. Of course, they are displayed by TED and can be crawled too, but they don't have an exact format so parsing them is not trivial.
