### ISSUE TITLE
Configuration: currency

### ISSUE THREAD

**Issue by KrzysztofMadejski** [petabyte-research/redflags#28]
Specify default currency code in configuration

Then change translations:
- [ ] charts.billionHUF - the currency should be stripped from messages and moved to the configuration
- [ ] charts.sumValueAxis - should have currency injected from config

**Comment by dzierzy** [comment]
fixed

**Comment by KrzysztofMadejski** [comment]
Currency should be specified in configuration (like [email contact](https://github.com/petabyte-research/redflags/commit/9e97fc4f131f8c1138ed3aa8b1506f319e392928)), not in translation.

**Comment by dzierzy** [comment]
currency moved to config file

**Comment by KrzysztofMadejski** [comment]
Dzięki!
