### ISSUE TITLE
Translate facebook plugin

### ISSUE THREAD

**Issue by KrzysztofMadejski** [petabyte-research/redflags#29]
- [ ] the facebook "like/share" plugin on the homepage  is in Hungarian. How to change it? should use current language.

**Comment by juzraai** [comment]
I've just solved it. You need to modify `site.facebookLanguages` configuration property.

Updated docs: http://docs.redflags.eu/developer/webapp/basic/#internationalization-i18n

**Comment by KrzysztofMadejski** [comment]
Works for me, cheers!
