### ISSUE TITLE
Import data from mojepanstwo.pl

### ISSUE THREAD

**Issue by KrzysztofMadejski** [petabyte-research/redflags#3]
Info
- Description of [API Mojego Państwa](https://mojepanstwo.pl/api)
- https://api-v3.mojepanstwo.pl/swagger.json
- Import data

Tasks:
- [ ] import datasets: zamowienia_publiczne, zamowienia_publiczne_dokumenty, zamowienia_publiczne_wykonawcy, zamowienia_publiczne_zamawiajacy
  - [ ] one-time import (archive data)
  - [ ] regular import (new tenders and offers since last import)

**Comment by KrzysztofMadejski** [comment]
Problemy z API:
1. kilka nieistniejących identyfikatorów zamawiającego (3 przypadki)
2. zapytanie: jak pobrać wszystkie identyfikatory z bazy zamówień  (`?fields[zamowienia_publiczne.id]=1` jakoś mi nie działa)
3. zapytanie: zamówienia zmienione od danej daty
   czy to możliwe? Nie widzę pola 'updated_at' w API; jak występują zmiany w zamówieniu to jest to jakoś oznaczane?  jak są np. oferty przechowywane?
4. co jest w zamówienia publiczne dokumenty? 

@danielmacyszyn pomożesz?

**Comment by dzierzy** [comment]
tymczasowo ściągam całość i wyparsowywuję identyfikatory wiec nie jest to bloker. Docelowo potrzebna usługa lub parametr dla samych ids, zarówno całość jak i od konkretnej daty

**Comment by dzierzy** [comment]
pobieranie zakresu identyfikatorów wciąż jest improwizowane, potrzebna działająca usługa która bez stronicowania poda zbiór identyfikatorów zamówień

**Comment by KrzysztofMadejski** [comment]
Teraz tego nie będziemy w API zmieniać, ale zawrę to jako rekomendacje do zmiany API.

**Comment by dzierzy** [comment]
done
