### ISSUE TITLE
Configuration: default amount scale

### ISSUE THREAD

**Issue by KrzysztofMadejski** [petabyte-research/redflags#30]
Millions Polish zloty doesn't make sense as a search query. Let's set it in the configuration `amount_scale=1000000`

Then change translations:
- [x] `notices.filter.value.placeholder=Value range in millions, e.g. '0-1000'` -> `notices.filter.value.placeholder.1000000`, `notices.filter.value.placeholder.1000`
- [x] `filter.email.noreply` - `noreply` is bad habit, it frustrates your clients. You should always provide a feedback link, ie. "In case of any problems please contact us at {contact_email}."

**Comment by juzraai** [comment]
> `filter.email.noreply` - `noreply` is bad habit, it frustrates your clients. You should always provide a feedback link, ie. "In case of any problems please contact us at {contact_email}."

[filter.email.contact](https://github.com/petabyte-research/redflags/blob/master/redflags-web/src/main/resources/messages_en.properties#L133) is already there and included in the [email template](https://github.com/petabyte-research/redflags/blob/master/redflags-web/src/main/resources/templates/filter-email.ftl#L44). :)

**Comment by KrzysztofMadejski** [comment]
Sorry, I've meant to copy this translaion into #35

**Comment by KrzysztofMadejski** [comment]
- [ ] it is also included in [helper sql](https://github.com/petabyte-research/redflags/blob/1cd401872d78be27365ca1fd947bac46d3aa2c7a/redflags-helper-tables.sql)

Which make it harder to make it configurable. Won't mySQL handle such big numbers?

**Comment by juzraai** [comment]
There's no problem with big numbers in MySQL. I put this dividing into the script to optimize the webapp. :)

I think it's possible to move out this dividing from the helper script and place it into the webapp instead, maybe at FTL level. I'll look into this.

**Comment by juzraai** [comment]
:point_right: http://docs.redflags.eu/developer/cookbook/#step-6-review-webapp-settings

Please also check out the new messages (see diff) + I modified the structure of the `rfwl_barplot` table in the helper SQL script.

**Comment by KrzysztofMadejski** [comment]
That's great @juzraai, thanks! :)
