### ISSUE TITLE
Configuration: contact email

### ISSUE THREAD

**Issue by KrzysztofMadejski** [petabyte-research/redflags#35]
Then change translations:
- [ ] "info @ redflags . eu" - should be taken [from the code](https://github.com/epforgpl/redflags/blob/master/redflags-web/src/main/resources/templates/index.ftl#L119) into the configuration (`contact_email` ?)
- [ ] `filter.email.noreply` - noreply is bad habit, it frustrates your clients. You should always provide a feedback link, ie. "In case of any problems please contact us at {contact_email}."

**Comment by juzraai** [comment]
Besides `filter.email.noreply`, `filter.email.contact` is already there with a similar sentence you wrote above; and I've just wired in `redflags.contact` property into `index.ftl`.

**Comment by KrzysztofMadejski** [comment]
Thank you, I will merge it in.

**Comment by KrzysztofMadejski** [comment]
Works for me, cheers!
