### ISSUE TITLE
Number of renewals

### ISSUE THREAD

**Issue by KrzysztofMadejski** [petabyte-research/redflags#39]
Co jest mapowane z mojego państwa na "Number of renewals"? [Tu](http://pl.redflags.transparencee.org/notice/2875798) się wyświetla 0, a nie kojarzę czegoś poobnego w BZP.. 

A może to pole powinno być nullem i nie być wyświetlane?

**Comment by dzierzy** [comment]
decyzja o wyświetlaniu jest podjęta tu:
https://github.com/epforgpl/redflags/blob/master/redflags-web/src/main/resources/templates/notice.ftl#L255

Jeśli dla BZP nie mamy takiego parametru to można ten element usunąć z warstwy prezentacji lub nie wyświetlać gdy wartość jest równa 0 lub zmodyfikować wartość domyślną na ujemną iteż to uwarunkować, przetrzymywana jest tu:
https://github.com/epforgpl/redflags/blob/master/redflags-engine/src/main/java/hu/petabyte/redflags/engine/model/noticeparts/ObjOfTheContract.java#L60

**Comment by KrzysztofMadejski** [comment]
Przez to, że jest `int`, a nie `Integer` to zawsze będzie wyświetlana. Wyłącz wyświetlanie w przypadku, gdy zero proszę.

**Comment by dzierzy** [comment]
cóż, wartość prymitywną tam zaprojektowano.
Naprawione

**Comment by KrzysztofMadejski** [comment]
Dzięki!
