### ISSUE TITLE
Flag description - handle long Polish explanations

### ISSUE THREAD

**Issue by KrzysztofMadejski** [petabyte-research/redflags#40]
We have long flag descriptions in Polish adaptation and they don't fit in popup. How about moving them in expanding panel beneath each flag?
- [ ] turn popup into expandable panel
- [ ] handle html in the descriptions

Link to the presented notice: http://pl.redflags.transparencee.org/notice/2875798
![rf-explanation](https://cloud.githubusercontent.com/assets/849975/18950686/5947df5c-8641-11e6-81f2-6acc6f58f26b.PNG)

**Comment by dzierzy** [comment]
fixed
