### ISSUE TITLE
Polish indicators: coding

### ISSUE THREAD

**Issue by KrzysztofMadejski** [petabyte-research/redflags#5]
Dependent on #4
- in the catalogue `pl` under https://github.com/petabyte-research/redflags/tree/master/redflags-engine/src/main/java/hu/petabyte/redflags/engine/gear/indicator/
- according to the guidelines provided by legal expert in #4 [here](https://docs.google.com/document/d/1SOsEifH9-aUD97L4i5or2-H4bwlFKBIiDMtkQRLtDhQ/edit)
- all encountered problems (a need to change db schema, aggregation mechanisms) mention in the document mentioned above in  "Challenges in indicators development" section - it will become a knowledgebase for future scaling

**Comment by dzierzy** [comment]
I propose to split tasks related to flagging by indicators as it's quite huge task, from exporting/db work, covered by #12 now.

**Comment by dzierzy** [comment]
please grant me an access to new indicators description

**Comment by dzierzy** [comment]
done
