### ISSUE TITLE
Guide in documentation: how to implement RedFlags in your country

### ISSUE THREAD

**Issue by KrzysztofMadejski** [petabyte-research/redflags#9]
Using the experience of deploying RedFlags in Poland create a guide on how to implement it in your country.

I guess that practically it will mean working on http://docs.redflags.eu/developer/cookbook/# so it become a list of steps and hints (ie. what to do if you import from TED, what to do if from other sources)

We need to accent the need of mapping fields to local schema (where to find it?)

**Comment by KrzysztofMadejski** [comment]
Reminder: Remember to include insights from #10

**Comment by dzierzy** [comment]
grant me edit rights, please

**Comment by KrzysztofMadejski** [comment]
@dzierzy here is the source code of the docs: https://github.com/petabyte-research/redflags/blob/master/redflags-docs/docs/developer/cookbook.md

Edit it on epforgpl fork and then we will merg it back.

**Comment by juzraai** [comment]
May I suggest you to create topic branches for those things you'd like to merge back to petabyte/redflags?

**Comment by KrzysztofMadejski** [comment]
Let's do it. I'll start with labels.

**Comment by KrzysztofMadejski** [comment]
@dzierzy says the existing documentation is enough.

I'll add the reference to #10 and link to overrides in engine's `epforgpl` packages done by @dzierzy

**Comment by KrzysztofMadejski** [comment]
_A guide for non-developers to be put on the landing page. Can be linked in the documentation as well._

Have you ever thought about developing a tool that would help you to detect corruption in advance? Red Flags is a tool that helps to detect potentially risky procurements with a set of algorithms. It is adaptable and we’ll tell you how to do it.

Is there a need, what impact do you want to achieve?
Although we are sure that Red Flags as a great and useful tool, you should first consider whether there is a need for it in your country / city. Therefore you should know whom you want to assist with the tool: Is it journalists? NGOs? Academics? Public administration? Do you want the tool to be used as a signalling tool for prevention? Do you want to engage citizens or concerned experts to evaluate investments? Or rather analyze how prone to corruption the procurement market is? Maybe you want to assess whether your procurements contains any risks before it is published? These are all very different scenarios. Be sure to define the need and the final outcome.

Is there data?
The most important input for the tool is data. The more you have the better the tool will be. Is procurement data available? Is it regularly updated? Is it published in open databases? Does its structure follow the same standards for the whole market you want to analyze? Are contracts and the amendments of notices available? Are there relevant external databases accessible, such as company registry or court decisions? Is it from a reliable source?

Are you an expert of public procurements?
A crucial part of the work is the set up of the right indicators. To achieve this you have to know about potential corruption risks and breaches of law in your country /city. Be sure to involve experts who can elaborate what you have to look at. Don’t forget to test and validate indicators before using them.

Are you a coder?
Implementing the tool needs a lot of coding which has to go hand in hand with the design of the indicators. You will need exact specifications to find the right information at the right place and to make all algorithms work they way you have imagined. This tool is developed in Java. Share our documentation with your coder, it will guide her/him through the process.

How much time / money / people do you need?
This depends of course on dozens of factors. You can create a basic adaption of the tool in 4-5 months, but the development of a complex system will take much more time. You will definitely need someone to shape the concept, manage the process, procurement experts to assist you in the indicator development, coders who will implement the indicators and testers who check and validate the indicators / outcomes. You can imagine that the price is going to depend on the experts you’ll have to pay. We find it unlikely that you can create a very basic adaption from less than 10k EUR. Don’t forget to think about sustainability! Such tools need updating whenever data formats, regulations, etc change. 

What are the main steps of implementation?

Formulate your needs / assess the availability and accessibility of data / assess risks / draw a concept
Get all relevant experts on board
Let them and other stakeholders assess the concept
Finalize the concept
Translate the code (if you use it in other language than English)
Build your database (follow standards, use OCDS)
Get the data
Design and implement the indicators
Test the indicators
Refine the algorithms and test again (and again and again)
Set up / adjust the user interface
Invite stakeholders to try it, make modifications if needed.
Let your audience and potential users know about the tool.

How can we assist you?
We have been working on Red Flags for more than 3 years and are happy to help you with questions or assist you in the development. Ask us!
